# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-28 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20190428_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimetable',
            name='user',
            field=models.IntegerField(default=0, verbose_name='接受用户'),
        ),
    ]
