# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-20 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20190428_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimetable',
            name='timetable',
            field=models.CharField(max_length=500, verbose_name='课表'),
        ),
    ]
