# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-20 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_auto_20190520_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimetable',
            name='timetable',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='课表'),
        ),
    ]
