# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-24 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
                'proxy': True,
            },
            bases=('courses.course',),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('cg', '常规课'), ('zt', '主题课')], default='', max_length=3, verbose_name='课程类型'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.CharField(max_length=300, verbose_name='课程详情'),
        ),
    ]
