# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-24 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190424_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.BooleanField(default=True, verbose_name='课程类别'),
        ),
    ]
