# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20190424_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.IntegerField(default=0, verbose_name='课程类别'),
        ),
    ]
