# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20190425_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='youneed_know',
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(default='', max_length=300, verbose_name='活动时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='课时数'),
        ),
    ]
