# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-26 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20190425_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='limit',
            field=models.IntegerField(default=0, verbose_name='人数上限'),
        ),
    ]
