# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-26 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_banner',
        ),
        migrations.AddField(
            model_name='course',
            name='is_detail',
            field=models.BooleanField(default=True, verbose_name='是否详细课程'),
        ),
    ]
