# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-28 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190428_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_vip',
            field=models.CharField(choices=[('vip', '会员'), ('unvip', '非会员')], default='', max_length=10, verbose_name='会员信息'),
        ),
    ]
