# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-26 10:12
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_courseorg_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='points',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='教学特点'),
        ),
    ]
