# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20190426_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.IntegerField(default=0, verbose_name='教师类别'),
        ),
    ]
